# Generated by Django 5.2.10 on 2026-01-18 01:23

import news.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الخبر')),
                ('content', models.TextField(verbose_name='محتوى الخبر')),
                ('image', models.ImageField(blank=True, null=True, upload_to=news.models.image_upload, verbose_name='صورة الخبر')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ النشر')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True, verbose_name='الرابط النصي')),
            ],
        ),
    ]
