# Generated by Django 5.2.10 on 2026-01-21 08:47

import news.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='content_en',
            field=models.TextField(blank=True, null=True, verbose_name='محتوى الخبر'),
        ),
        migrations.AddField(
            model_name='news',
            name='image_en',
            field=models.ImageField(blank=True, null=True, upload_to=news.models.image_upload, verbose_name='صورة الخبر'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='عنوان الخبر'),
        ),
    ]
