# Generated by Django 5.2.10 on 2026-01-21 08:50

import news.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_news_content_en_alter_news_image_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='content_en',
            field=models.TextField(blank=True, null=True, verbose_name='Content In English'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image_en',
            field=models.ImageField(blank=True, null=True, upload_to=news.models.image_upload, verbose_name='News Picture English'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='News title English'),
        ),
    ]
