# Generated by Django 5.2.10 on 2026-01-21 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_news_content_en_alter_news_image_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='slug_en',
            field=models.SlugField(allow_unicode=True, blank=True, null=True, verbose_name='slug_en'),
        ),
    ]
