# Generated by Django 5.2.10 on 2026-01-22 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_news_slug_en'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'permissions': [('can_publish_news', 'Can publish news')]},
        ),
    ]
