# Generated by Django 5.2.10 on 2026-01-18 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الهاتف')),
                ('volunteer_type', models.CharField(choices=[('individual', 'فرد'), ('group', 'مجموعة')], default='individual', max_length=10, verbose_name='نوع التطوع')),
                ('group_size', models.PositiveIntegerField(blank=True, help_text='اكتب عدد أعضاء المجموعة إذا كان التطوع جماعي', null=True, verbose_name='عدد أعضاء المجموعة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التسجيل')),
            ],
        ),
    ]
