# Generated by Django 5.2.10 on 2026-01-18 05:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='name',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(3, message='الاسم يجب أن يكون على الأقل 3 أحرف'), django.core.validators.RegexValidator('^[\\u0621-\\u064A\\s]+$', message='الاسم يجب أن يحتوي على حروف عربية فقط')], verbose_name='الاسم'),
        ),
    ]
