# Generated by Django 5.2.10 on 2026-01-18 05:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0002_alter_volunteer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='name',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(3, message='الاسم يجب أن يكون على الأقل 3 أحرف')], verbose_name='الاسم'),
        ),
    ]
