# Generated by Django 5.2.10 on 2026-01-18 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0003_alter_volunteer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='email',
            field=models.EmailField(error_messages={'invalid': 'الرجاء إدخال بريد إلكتروني صالح'}, max_length=254, verbose_name='البريد الإلكتروني'),
        ),
    ]
