# Generated by Django 5.2.10 on 2026-01-18 05:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0006_alter_volunteer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='email',
            field=models.EmailField(error_messages={'blank': 'البريد الإلكتروني مطلوب', 'null': 'البريد الإلكتروني مطلوب'}, max_length=254, validators=[django.core.validators.EmailValidator(message='الرجاء إدخال بريد إلكتروني صالح')], verbose_name='البريد الإلكتروني'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='group_size',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1, message='عدد أعضاء المجموعة يجب أن يكون 1 أو أكثر')], verbose_name='عدد أعضاء المجموعة'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='name',
            field=models.CharField(error_messages={'blank': 'الاسم مطلوب', 'null': 'الاسم مطلوب'}, max_length=200, validators=[django.core.validators.MinLengthValidator(3, message='الاسم يجب أن يكون على الأقل 3 أحرف')], verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='phone',
            field=models.CharField(default=1, error_messages={'blank': 'رقم الهاتف مطلوب', 'null': 'رقم الهاتف مطلوب'}, max_length=15, validators=[django.core.validators.RegexValidator('^\\d{8,15}$', message='رقم الهاتف يجب أن يكون بين 8 و15 رقم')], verbose_name='رقم الهاتف'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='volunteer_type',
            field=models.CharField(choices=[('individual', 'فرد'), ('group', 'مجموعة')], error_messages={'blank': 'نوع التطوع مطلوب', 'null': 'نوع التطوع مطلوب'}, max_length=10, verbose_name='نوع التطوع'),
        ),
    ]
