# Generated by Django 5.2.10 on 2026-01-18 05:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0007_alter_volunteer_email_alter_volunteer_group_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='email',
            field=models.EmailField(error_messages={'blank': 'البريد الإلكتروني مطلوب', 'invalid': 'الرجاء إدخال بريد إلكتروني صالح'}, max_length=50, verbose_name='البريد الإلكتروني'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='group_size',
            field=models.PositiveIntegerField(blank=True, help_text='اكتب عدد أعضاء المجموعة إذا كان التطوع جماعي', null=True, verbose_name='عدد أعضاء المجموعة'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='name',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(3, message='الاسم يجب أن يكون على الأقل 3 أحرف')], verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='volunteer_type',
            field=models.CharField(choices=[('individual', 'فرد'), ('group', 'مجموعة')], default='individual', max_length=10, verbose_name='نوع التطوع'),
        ),
    ]
