# Generated by Django 5.2.10 on 2026-01-25 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_reference',
            new_name='merchant_order_id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='status',
            new_name='payment_status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='transaction_id',
        ),
    ]
