# Generated by Django 5.2.10 on 2026-01-27 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_rename_order_reference_order_merchant_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='donor_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
