# Generated by Django 5.2.10 on 2026-01-18 00:30

import donations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0003_donation_is_paid_donation_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='image',
            field=models.ImageField(upload_to=donations.models.image_upload, verbose_name='صورة الحالة'),
        ),
    ]
