# Generated by Django 5.2.10 on 2026-01-18 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0004_case_slug_alter_case_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, null=True),
        ),
    ]
