# Generated by Django 5.2.10 on 2026-01-18 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0005_alter_case_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
