# Generated by Django 5.2.10 on 2026-01-18 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0006_alter_case_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='الرابط النصي من العنوان'),
        ),
    ]
