# Generated by Django 5.2.10 on 2026-01-18 04:46

import donations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0007_alter_case_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='image',
            field=models.ImageField(max_length=200, upload_to=donations.models.image_upload, verbose_name='صورة الحالة'),
        ),
    ]
