# Generated by Django 5.2.10 on 2026-01-21 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0009_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='custom_id',
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
