# Generated by Django 5.2.10 on 2026-01-21 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0010_cartitem_custom_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='custom_id',
        ),
    ]
