# Generated by Django 5.2.10 on 2026-01-21 02:31

import donations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0011_remove_cartitem_custom_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='image',
            field=models.ImageField(upload_to=donations.models.image_upload, verbose_name='صورة الحالة'),
        ),
        migrations.AlterField(
            model_name='case',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='الرابط النصي'),
        ),
    ]
