# Generated by Django 5.2.10 on 2026-01-21 02:40

import donations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0012_alter_case_image_alter_case_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='image',
            field=models.ImageField(max_length=200, upload_to=donations.models.image_upload, verbose_name='صورة الحالة'),
        ),
        migrations.AlterField(
            model_name='case',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='الرابط النصي من العنوان'),
        ),
    ]
