# Generated by Django 5.2.10 on 2026-01-21 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0013_alter_case_image_alter_case_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
