# Generated by Django 5.2.10 on 2026-01-26 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0014_delete_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
