# Generated by Django 5.2.10 on 2026-01-22 06:36

import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0002_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Directors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('badge', models.CharField(blank=True, max_length=20, null=True, verbose_name='Badge')),
                ('position', models.CharField(max_length=30, verbose_name='Position')),
                ('image', models.ImageField(blank=True, null=True, upload_to=home.models.image_upload, verbose_name='Image')),
                ('description', models.TextField(blank=True, max_length=30, null=True, verbose_name='Description')),
                ('expertise', models.CharField(blank=True, max_length=30, null=True, verbose_name='Expertise')),
                ('facebook', models.CharField(blank=True, null=True, verbose_name='Facebook')),
                ('linkedin', models.CharField(blank=True, null=True, verbose_name='Linked In')),
                ('x', models.CharField(blank=True, null=True, verbose_name='X')),
            ],
        ),
    ]
