# Generated by Django 5.2.10 on 2026-01-22 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directors',
            name='badge',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Badge'),
        ),
        migrations.AlterField(
            model_name='directors',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='directors',
            name='expertise',
            field=models.CharField(blank=True, null=True, verbose_name='Expertise'),
        ),
        migrations.AlterField(
            model_name='directors',
            name='position',
            field=models.CharField(verbose_name='Position'),
        ),
    ]
