# Generated by Django 5.2.10 on 2026-01-22 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_directors_badge_alter_directors_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directors',
            name='name',
            field=models.CharField(max_length=40, verbose_name='Name'),
        ),
    ]
