# Generated by Django 5.2.10 on 2026-01-22 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_directors_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Directors',
            new_name='Board',
        ),
    ]
