# Generated by Django 5.2.10 on 2026-01-27 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_views_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productorder',
            name='buyer_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='productorder',
            name='payment_method',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
