# Generated by Django 5.2.10 on 2026-01-27 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_productorder_buyer_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productorder',
            name='buyer_name',
        ),
        migrations.AddField(
            model_name='productorder',
            name='donor_name',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
