# Generated by Django 5.2.10 on 2026-01-27 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_productorder_buyer_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductOrder',
            new_name='Donation',
        ),
    ]
